import logging
from typing import Any

logger = logging.getLogger(__name__)


async def dispatch_notifications(notifications: list[dict[str, Any]]) -> None:
    """Dispatches notifications generated by the LangGraph pipeline.

    This service is decoupled from the agent logic, serving as the central adapter
    where the Municipal Corporation's IT department can register custom SMS, email,
    or ticketing gateway integrations.
    """
    if not notifications:
        logger.info("No notifications generated for this analysis run.")
        return

    logger.info(f"Notification Dispatcher: Received {len(notifications)} payload(s) to process.")

    for notif in notifications:
        channel = notif.get("channel", "unknown")
        subject = notif.get("subject", "No Subject")
        body = notif.get("body", "")
        property_id = notif.get("property_id", "unknown")

        logger.info(f"Processing notification payload for Property ID: {property_id} via channel: {channel}")

        # ── 1. OFFICER TASK / INTERNAL TICKETS ────────────────────────────────
        if channel == "officer_task":
            logger.info(f"Dispatching Internal Ticket [Subject: {subject}]")
            # TODO: Plug in Municipal Corporation's internal task tracking API here
            # Example:
            # await munc_corp_workflow_client.create_ticket(
            #     title=subject,
            #     description=body,
            #     assigned_to=notif.get("risk_level", "low")
            # )

        # ── 2. SMS NOTIFICATIONS ──────────────────────────────────────────────
        elif channel == "sms":
            logger.info(f"Dispatching SMS Alert [Subject: {subject}]")
            # TODO: Plug in NIC SMS portal or custom telecom gateway API here
            # Example:
            # await nic_sms_client.send_message(
            #     recipient=notif.get("phone", "officer_phone"),
            #     text=body
            # )

        # ── 3. EMAIL/WHATSAPP NOTIFICATIONS ───────────────────────────────────
        elif channel in ("email", "whatsapp"):
            logger.info(f"Dispatching {channel.upper()} Message [Subject: {subject}]")
            # TODO: Plug in WhatsApp Business API or SMTP relay here
            # Example:
            # await whatsapp_client.send_template(
            #     to=notif.get("phone"),
            #     template="leakage_alert",
            #     parameters=[property_id, notif.get("risk_level")]
            # )

        else:
            logger.warning(f"Unsupported notification channel: {channel}. Logging payload to console.")

        # Log trace to console/docker output for verification
        print("\n==========================================")
        print(f"📢 [DISPATCH NOTIFICATION - {channel.upper()}]")
        print(f"Subject : {subject}")
        print(f"Body    :\n{body}")
        print("==========================================\n")
