/** UI labels — kept in English. Database values (names, addresses) remain Marathi. */

export function riskLevelMr(level: string | null | undefined): string {
  if (!level) return '—'
  const map: Record<string, string> = {
    Critical: 'Critical',
    High: 'High',
    Medium: 'Medium',
    Low: 'Low',
    critical: 'Critical',
    high: 'High',
    medium: 'Medium',
    low: 'Low',
  }
  return map[level] || level
}

export const mr = {
  appName: 'RevenueGuard',
  dashboard: 'Dashboard',
  properties: 'Properties',
  propertyDetail: 'Property Detail',
  cases: 'Investigation Cases',
  map: 'Map',
  reports: 'Reports',
  settings: 'Settings',
  login: 'Login',
  searchProperties: 'Search properties…',
  allProperties: 'All Properties',
  allUsageTypes: 'All Usage Types',
  allWards: 'All Wards',
  exemptionAll: 'Exemption: All',
  exempted: 'Exempted',
  notExempted: 'Not Exempted',
  clear: 'Clear',
  owner: 'Owner',
  address: 'Address',
  ward: 'Ward',
  usage: 'Usage Type',
  declaredUsage: 'Declared Usage',
  area: 'Area (Declared / Survey)',
  riskScore: 'Risk Score',
  risk: 'Risk',
  impact: 'Impact',
  view: 'View',
  propertyUid: 'Property ID',
  declaredArea: 'Declared Area',
  gisArea: 'Surveyed Area',
  taxDemand: 'Tax Demand',
  taxPaid: 'Tax Paid',
  arrears: 'Arrears',
  outstanding: 'Outstanding',
  payments: 'Payments',
  paymentDate: 'Payment Date',
  paymentMode: 'Payment Mode',
  noData: 'No data available',
  loading: 'Loading…',
  totalProperties: 'Total Properties',
  revenueAtRisk: 'Revenue at Risk',
  urgentCases: 'Urgent Cases',
  recoveredRevenue: 'Recovered Revenue',
  mismatch: 'Mismatch',
  updated: 'Updated',
  sqm: 'sq.m.',
} as const
